name: Assistant

on:
  push:
    tags:
      - '*'

jobs:
  build-Assistant:
    runs-on: windows-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Release Version
      id: get_version
      shell: bash
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

    - name: Build Release
      run:  scripts/build.bat

    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        filename: assistant-${{ steps.get_version.outputs.VERSION }}.zip
        path: release

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: assistant-${{ steps.get_version.outputs.VERSION }}.zip
        tag: ${{ github.ref }}
        file_glob: true
        prerelease: true